version: 1.0.{build}
platform: Any CPU
build_script:
- cmd: build.cmd
test_script:
- cmd: test.cmd
notifications:
- provider: Email
  to:
  - dimerouh@gmail.com
  subject: BookMate build notification
  message: Yo, my friend.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false